version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run:
          name: Running makepkg
          command: makepkg -s
      - store_artifacts:
          path: *.tar.xz

