version: 2
jobs:
  build:
    docker:
      - image: martinnyborg/archlinux-kernel-builder
    steps:
      - checkout
      - run:
          name: Running makepkg
          command: |
            makepkg -s

