version: 2
jobs:
  build:
    docker:
      - image: archlinux/base
    steps:
      - checkout
      - run:
          name: Running makepkg
          command: |
            pacman -Sy --needed --noconfirm sudo # Install sudo
            useradd builduser -m # Create the builduser
            passwd -d builduser # Delete the buildusers password
            su builduser
            makepkg -s
